### ISSUE TITLE
"subsection not found" error - Can't find START_MARKER

### ISSUE THREAD

**Issue by mostafaelhoushi** [ithemal/Ithemal#57]
I have created a simple C file:
```
int main() {
	int x = 3;
	int y = 3*x + 255;
	if (y > 4) {
		x++;
		x = x + 22*y;
	}
	else {
		y++;
		y = y + 22*x;
	}
	return y;
}
```

then built it using:
```
gcc add.c
```

then when I try to run:
```
python learning/pytorch/ithemal/predict.py --verbose --model ./models/paper/haswell/predictor.dump --model-data ./models/paper/haswell/trained.mdl --file ./test_code/add/a.out 
```

I get this error:
```
Traceback (most recent call last):
  File "learning/pytorch/ithemal/predict.py", line 152, in <module>
    main()
  File "learning/pytorch/ithemal/predict.py", line 149, in main
    predict(model, data, fname, args.verbose)
  File "learning/pytorch/ithemal/predict.py", line 67, in predict
    datum = read_basic_block(fname, data, verbose)
  File "learning/pytorch/ithemal/predict.py", line 55, in read_basic_block
    start_pos = code.index(START_MARKER)
ValueError: subsection not found
```

Please note that I am not using docker. I went through the steps of running the build scripts and installing necessary packages that were needed.

**Comment by alexrenda** [comment]
Ithemal uses the same convention as IACA to denote what code should be predicted, and only predicts for individual basic blocks.

Check out https://github.com/ithemal/Ithemal/blob/master/learning/pytorch/examples/example.c for an example of doing this when compiling from C -- for instance, if you wanted to predict the throughput of the code in the true branch of the if, your code might end up looking like this:

```
/**
content of iacaMarks.h
**/

#if defined (__GNUC__) 
#define IACA_SSC_MARK( MARK_ID )						\
__asm__ __volatile__ (									\
					  "\n\t  movl $"#MARK_ID", %%ebx"	\
					  "\n\t  .byte 0x64, 0x67, 0x90"	\
					  : : : "memory" );

#else
#define IACA_SSC_MARK(x) {__asm  mov ebx, x\
	__asm  _emit 0x64 \
	__asm  _emit 0x67 \
	__asm  _emit 0x90 }
#endif

#define IACA_START {IACA_SSC_MARK(111)}
#define IACA_END {IACA_SSC_MARK(222)}

#ifdef _WIN64
#include <intrin.h>
#define IACA_VC64_START __writegsbyte(111, 111);
#define IACA_VC64_END   __writegsbyte(222, 222);
#endif


/**
Content of add.c
**/

int main() {
	int x = 3;
	int y = 3*x + 255;
	if (y > 4) {
                IACA_START
		x++;
		x = x + 22*y;
                IACA_END
	}
	else {
		y++;
		y = y + 22*x;
	}
	return y;
}

```

**Comment by mostafaelhoushi** [comment]
Thank you @alexrenda for your quick response. Highly appreciate that!

I have copied the code you provided, and now getting a different error:
```
~/Ithemal$ python learning/pytorch/ithemal/predict.py --verbose --model ./models/paper/haswell/predictor.dump --model-data ./models/paper/haswell/trained.mdl --file ./learning/pytorch/examples/add
Traceback (most recent call last):
  File "learning/pytorch/ithemal/predict.py", line 152, in <module>
    main()
  File "learning/pytorch/ithemal/predict.py", line 149, in main
    predict(model, data, fname, args.verbose)
  File "learning/pytorch/ithemal/predict.py", line 67, in predict
    datum = read_basic_block(fname, data, verbose)
  File "learning/pytorch/ithemal/predict.py", line 64, in read_basic_block
    return datum_of_code(data, binascii.b2a_hex(block_binary), verbose)
  File "learning/pytorch/ithemal/predict.py", line 49, in datum_of_code
    data.prepare_data(fixed=True, progress=False)
  File "/home/m00476721/Ithemal/learning/pytorch/data/data_cost.py", line 65, in prepare_data
    split_code_intel = itertools.chain((code_intel or '').split('\n'), itertools.repeat(''))
TypeError: a bytes-like object is required, not 'str'
```

**Comment by alexrenda** [comment]
What version of Python are you using? The version in the Docker is Python 2, we didn't test all of the scripts on python 3.

**Comment by mostafaelhoushi** [comment]
I am using Python 3. I wasn't able to get the docker on my system, and wasn't able to run using Python 2. So I actually changed a lot of the code to get it working on Python 3. Let me try to either fix this bug or switch back to docker,

**Comment by mostafaelhoushi** [comment]
I have fixed the remaining bugs that were related to incomplete conversion from Python3 to Python 3 and got the example code working. Thanks for all your help!

I have created a fork with the code converted to Python3 and updated the README, in case anyone is interested:
https://github.com/mostafaelhoushi/Ithemal
